Citizen.CreateThread(function()
    AddTextEntryByHash(0x005F77A9, "Carbon Sunstrip")
    AddTextEntryByHash(0x006A5C15, "Day Cruiser")
    AddTextEntryByHash(0x00705EA5, "Sec. Strakes w/ Race Diffuser")
    AddTextEntryByHash(0x007F25E6, "Plastic w/ Sec. Winged Race")
    AddTextEntryByHash(0x008877FF, "HSW Sunstrip")
    AddTextEntryByHash(0x0088F9C2, "Primary Tuner Wing")
    AddTextEntryByHash(0x00FA7796, "Primary w/ Sec. Light Tape")
    AddTextEntryByHash(0x00FC8D2A, "Winged Race Splitter")
    AddTextEntryByHash(0x01627FBA, "Sec. Trimmed Carb. Splitter")
    AddTextEntryByHash(0x01CE2594, "Secondary Finned Skirts")
    AddTextEntryByHash(0x01D270BF, "Heavy Duty Diffuser")
    AddTextEntryByHash(0x02314FC2, "Shed Meister")
    AddTextEntryByHash(0x031F18AB, "Grille MAX")
    AddTextEntryByHash(0x033E8179, "Secondary Bolt-On Arches")
    AddTextEntryByHash(0x039D3AEE, "Carbon Wing")
    AddTextEntryByHash(0x03F1A3CF, "The Monarch")
    AddTextEntryByHash(0x04133C2C, "Vintage Mirrors")
    AddTextEntryByHash(0x041823EB, "Carbon Heat Extractor")
    AddTextEntryByHash(0x042E8355, "Plastic Street Ducktail")
    AddTextEntryByHash(0x04836A64, "Atomic Racing Cap")
    AddTextEntryByHash(0x04A90B41, "Sport Bumper MK II")
    AddTextEntryByHash(0x04C3D5A1, "Backside Surf Co.")
    AddTextEntryByHash(0x04C4E06C, "Plastic Street Wing")
    AddTextEntryByHash(0x04D1D6E5, "Carbon Bed Cover")
    AddTextEntryByHash(0x0502EEAA, "Xero Performance")
    AddTextEntryByHash(0x054654FA, "Carbon Wing Vent")
    AddTextEntryByHash(0x056A2E4E, "Slashed Blast Pipes")
    AddTextEntryByHash(0x05734820, "Ducktail Spoiler")
    AddTextEntryByHash(0x05E54419, "Touring Triple Tip Exhaust")
    AddTextEntryByHash(0x0663B5FB, "Grand Havoc")
    AddTextEntryByHash(0x067A7A2A, "Tint 5")
    AddTextEntryByHash(0x068974BC, "HSW Hood III")
    AddTextEntryByHash(0x06B1C48F, "Street Mirrors")
    AddTextEntryByHash(0x071A4568, "Carbon Sport Mirrors")
    AddTextEntryByHash(0x075CF408, "Radial Fairing w/ Screen")
    AddTextEntryByHash(0x076EA92D, "Carbon Lip Skirts")
    AddTextEntryByHash(0x0783307A, "Cruiser Crash Bar")
    AddTextEntryByHash(0x078B50EC, "Carbon Race Splitter")
    AddTextEntryByHash(0x07E48999, "Plastic Arm Race Wing")
    AddTextEntryByHash(0x084E0216, "Trim Sports Diffuser")
    AddTextEntryByHash(0x084E0D91, "Carbon Street Splitter")
    AddTextEntryByHash(0x088D788C, "Ragga Rum Racing")
    AddTextEntryByHash(0x08D933CB, "Mesh Grille")
    AddTextEntryByHash(0x0A7C2D4E, "Chrome Horizontal & Vertical")
    AddTextEntryByHash(0x0A2819B9, "Santa Skull Sweater")
    AddTextEntryByHash(0x0AD824AE, "Street Skirts")
    AddTextEntryByHash(0x0B0B1116, "Carbon Stock Arches")
    AddTextEntryByHash(0x0B3B71B7, "Amigas Racing")
    AddTextEntryByHash(0x0B3C810F, "Cowled Vented Hood")
    AddTextEntryByHash(0x0B502D12, "Secondary Street Splitter")
    AddTextEntryByHash(0x0B76624C, "Shaded Meister")
    AddTextEntryByHash(0x0C3F3A1B, "Full Cage")
    AddTextEntryByHash(0x0C4DED62, "Secondary GT MK II Wing")
    AddTextEntryByHash(0x0CC8BB86, "Oval Intake Bugcatcher")
    AddTextEntryByHash(0x0CC8D0AA,
        "Don't let the eye-watering acceleration or barely legal ground clearance fool you; the Suzume is a road-ready production car through and through. How Överflöd got it approved in Sweden is unclear, although suggestions that its total lack of safety features is an attempt to cull the population of epically stupid millionaires have been publicly denied by their marketing team, who recommend that you simply enjoy the thrill of reaching breakneck speeds in half a second with the absolute certainty that the slightest bump in the road will total you.~n~~n~- Missile Lock-On Jammer available")
    AddTextEntryByHash(0x0D09D554, "Carbon Rear Bumper")
    AddTextEntryByHash(0x0D2B07CB, "Skirted Splitter")
    AddTextEntryByHash(0x0D2E7CBC, "Lip Splitter")
    AddTextEntryByHash(0x0D91FD0F, "Carbon Shaker Hood")
    AddTextEntryByHash(0x0DACA966, "Track Exhaust")
    AddTextEntryByHash(0x0DF2EE4A, "Carbon Competition Ducktail")
    AddTextEntryByHash(0x0E0E1BEE, "Red Stripe")
    AddTextEntryByHash(0x0E21C4AA, "Tint 8")
    AddTextEntryByHash(0x0E88FAD6, "Secondary Strakes Diffuser")
    AddTextEntryByHash(0x0E95BDDD, "Hands On Car Wash Cap")
    AddTextEntryByHash(0x0E472928, "Black On The Pisswasser Tee")
    AddTextEntryByHash(0x0EEF2E66, "Reduced Stock Splitter")
    AddTextEntryByHash(0x0F1DB93B, "Vented Hood")
    AddTextEntryByHash(0x0F2C525E, "GT MK2 Mirrors")
    AddTextEntryByHash(0x0F3A29A5, "Winged Race w/ Sec. Trim")
    AddTextEntryByHash(0x0F3C4AB1, "Primary Winged Skirt")
    AddTextEntryByHash(0x0F4E2A04, "Rake Splitter")
    AddTextEntryByHash(0x0F6BE44C, "Primary Roof")
    AddTextEntryByHash(0x0F71FD9D, "The Bobcat Security Driver")
    AddTextEntryByHash(0x0FF3C1DF, "Finned Skirts")
    AddTextEntryByHash(0x0FFEDBA2, "Carbon Extreme Downforce BGW")
    AddTextEntryByHash(0x1A25BE9C, "Carbon Wrapped Exhausts")
    AddTextEntryByHash(0x1A8209B5, "Diffuser w/ Sec. Trim")
    AddTextEntryByHash(0x1A10529C, "Medium Mudguard")
    AddTextEntryByHash(0x1AB70976, "Cowl Induction w/ Turbos")
    AddTextEntryByHash(0x1AE4CD06, "WEED SHOP")
    AddTextEntryByHash(0x1AF8A366, "Carbon Splitter")
    AddTextEntryByHash(0x1B0EAE5A, "Higgins Helitours Tee")
    AddTextEntryByHash(0x1B21DD4F, "Pluck Me Sweater")
    AddTextEntryByHash(0x1B568D9B, "Cutout Ducktail")
    AddTextEntryByHash(0x1B7516F3, "Best Waifu")
    AddTextEntryByHash(0x1BAA70AC, "Carbon Hexagon Vented Trunk")
    AddTextEntryByHash(0x1BE86037, "Tint 7")
    AddTextEntryByHash(0x1C030B53, "Blue Manor Shorts")
    AddTextEntryByHash(0x1C18FCE2, "LSCM Cheetah Classic")
    AddTextEntryByHash(0x1C7087A1, "Carbon Hood")
    AddTextEntryByHash(0x1CE848CE, "Simple Skirt")
    AddTextEntryByHash(0x1D46B58D, "Bolt-On Arches")
    AddTextEntryByHash(0x1DBC5CEC, "Pursuit Crash Bar")
    AddTextEntryByHash(0x1DC5D777, "Los Santos Machine")
    AddTextEntryByHash(0x1E775D5E, "Race Hood")
    AddTextEntryByHash(0x1F8DDAD6, "Secondary Twin Intake Hood")
    AddTextEntryByHash(0x1F89D9FD, "Copper Exhaust")
    AddTextEntryByHash(0x1F152FA4, "Secondary Sports Diffuser")
    AddTextEntryByHash(0x1F725965, "Rugged MK2 Rack Roof Basket")
    AddTextEntryByHash(0x1FADBF2D, "White Stripe")
    AddTextEntryByHash(0x1FD3E19C,
        "Let's not beat around the bush. We know our customer base. We know you. We know that bragging about the improved agility, the 6-speed transmission, the unparalleled clutch durability, or the diversity of torque outputs would only put you to sleep. So let us put it this way: with the Sentinel GTS, you'll be able to cut more people off, at greater speeds, under the influence of more narcotics, eluding more squad cars, making more headlines, and causing more collateral damage - all while giving less of a shit than ever before.~n~~n~- Missile Lock-On Jammer available")
    AddTextEntryByHash(0x2AAFCC69, "Manor Drifter")
    AddTextEntryByHash(0x2AE0689F, "Plastic Razor Grille")
    AddTextEntryByHash(0x2AE101FE, "Skirt w/ Secondary Trim")
    AddTextEntryByHash(0x2B4C2900, "Secondary Tuner Ducktail")
    AddTextEntryByHash(0x2B5AE73D, "Extended Splitter w/ Canards")
    AddTextEntryByHash(0x2B129FFD, "Minami")
    AddTextEntryByHash(0x2B169BA5, "Carbon Sculpted Roof")
    AddTextEntryByHash(0x2B375DD2, "Angled Blast Pipes")
    AddTextEntryByHash(0x2B2446DF, "Secondary Custom Hood")
    AddTextEntryByHash(0x2BCAF611, "Small Mudguard")
    AddTextEntryByHash(0x2BCFCC40, "Secondary Side Bars")
    AddTextEntryByHash(0x2BF8A3F9, "Race Wing")
    AddTextEntryByHash(0x2C6ACFB4,
        "We thought they couldn't do it. After the Karin engineers overstepped the mark with the last Everon model, unleashing a street truck so aggressive that it defied every known rule of automotive engineering and civic responsibility, they went ahead and outdid themselves. The RS takes the small-dick, big-ego energy of the last iteration, drops it down so close to the asphalt you'll need a barrel of silicone lube to get over the bump in your garage door, and amplifies its fuck-you styling to a level as obnoxious as the guy blasting reactionary country music on Vespucci Beach.~n~~n~- Missile Lock-On Jammer available")
    AddTextEntryByHash(0x2C7B3AE1, "Secondary Street Hood")
    AddTextEntryByHash(0x2C44AD3A, "Secondary Diffuser")
    AddTextEntryByHash(0x2C543D86, "Blue Manor Shorts")
    AddTextEntryByHash(0x2C908893, "Atomic Racing Bomber Zipped")
    AddTextEntryByHash(0x2CB1F9D3, "Competition Hood")
    AddTextEntryByHash(0x2CC52C4C, "THIS LABEL NEEDS TO BE HERE !!!")
    AddTextEntryByHash(0x2CD3CB21, "Carbon Sports Diffuser")
    AddTextEntryByHash(0x2CD9C864, "Round Wing Mounted Mirrors")
    AddTextEntryByHash(0x2CF3ADEF, "Ram Air Hood")
    AddTextEntryByHash(0x2D064741, "Tint 9")
    AddTextEntryByHash(0x2D2B0389, "Scribble")
    AddTextEntryByHash(0x2D8B3B1F, "Gravel Special")
    AddTextEntryByHash(0x2E30AFAE, "LS Death Metal Shorts")
    AddTextEntryByHash(0x2E80F8ED, "The Chief")
    AddTextEntryByHash(0x2EA9790D, "Carbon Twin Intake Hood")
    AddTextEntryByHash(0x2EB6AC2D, "Secondary Hood")
    AddTextEntryByHash(0x2F4BED95, "Carbon Simple Skirt")
    AddTextEntryByHash(0x2FB05A5C, "Carbon Molded Arches")
    AddTextEntryByHash(0x2FD4B46B, "Secondary High Race Wing")
    AddTextEntryByHash(0x3AB61DBA, "Tint 9")
    AddTextEntryByHash(0x3AC046CC, "Plastic Tuner Ducktail")
    AddTextEntryByHash(0x3AF4014F, "Rally Splitter")
    AddTextEntryByHash(0x3B6E3E1E, "Secondary Winged Skirt")
    AddTextEntryByHash(0x3B34F2A9, "Racing Division")
    AddTextEntryByHash(0x3BE19D09, "Chrome Trim")
    AddTextEntryByHash(0x3C0C30B7, "Race Bumper")
    AddTextEntryByHash(0x3C75A527, "Winged Skirt w/ Sec. Trim")
    AddTextEntryByHash(0x3CA1DB2E, "Carbon Vented Hood")
    AddTextEntryByHash(0x3D00EB85, "The Buccaneer")
    AddTextEntryByHash(0x3D5CD1A7, "Secondary Cutout Ducktail")
    AddTextEntryByHash(0x3D858889, "Aluminum Tipped Exhausts")
    AddTextEntryByHash(0x3DD013F5, "Secondary Grille Insert")
    AddTextEntryByHash(0x3ED9A6E6, "Pride Up North")
    AddTextEntryByHash(0x3EDB41AF,
        "Inflicting justice and perpetrating peace can be hot and heavy work, and sometimes you'd rather not be sweating your balls off behind the wheel of an LSPD cruiser. Hop on the classic Police Bike and allow the breeze of the Pacific to cool your neck and the refreshing smog of the city to fill your lungs. It also offers exceptional agility, whether you're conducting that unnecessary sobriety test on the hottie on Vespucci Boulevard or ignoring that armed robbery dispatch altogether.~n~~n~- Missile Lock-On Jammer available~n~- Dispatch Work available~n~- Purchase unlocks the exclusive Summer Highway Patrol outfit~n~~n~Please note: This vehicle can only be modified in properties you own and has a resale value of $0.")
    AddTextEntryByHash(0x3F1D888F, "Oval Exhaust")
    AddTextEntryByHash(0x3F59EBC9, "Carbon Heavy Duty w/ Sec. Trim")
    AddTextEntryByHash(0x3F16204C, "Chrome Hexagon Mesh Grille")
    AddTextEntryByHash(0x3FF021E8, "Crossbar w/ Horizontal Grille")
    AddTextEntryByHash(0x4A7FED86, "Hawk Grille")
    AddTextEntryByHash(0x4A441FBC, "Large Splitter")
    AddTextEntryByHash(0x4A844E5F, "Sec. Pulse Vented Trunk")
    AddTextEntryByHash(0x4A28114C, "Secondary Splitter")
    AddTextEntryByHash(0x4AA20DF7, "Primary Trunk Wing")
    AddTextEntryByHash(0x4AD938F7, "Angled Blast Pipes")
    AddTextEntryByHash(0x4AE3F7B2, "Secondary Vented Hood")
    AddTextEntryByHash(0x4AF5FC13, "Simple Hood")
    AddTextEntryByHash(0x4B5ABF9C, "Secondary Sunstrip")
    AddTextEntryByHash(0x4B79A0B6, "Black Hexagon Mesh")
    AddTextEntryByHash(0x4C367D10, "Sport Stripes Black")
    AddTextEntryByHash(0x4C7211AF, "Secondary Race Wing")
    AddTextEntryByHash(0x4CDDAC2B, "Grille Simple")
    AddTextEntryByHash(0x4D2CA5C0, "Carbon Rally Splitter")
    AddTextEntryByHash(0x4DA6B6DF, "Bolt-On Vent Hood")
    AddTextEntryByHash(0x4E3E4163, "Chrome Winged Race")
    AddTextEntryByHash(0x4E28B4D6, "Competition Wing")
    AddTextEntryByHash(0x4EE87F51, "Carbon Bolt-On MK II")
    AddTextEntryByHash(0x4F8660E1, "Carbon Competition Splitter")
    AddTextEntryByHash(0x4F8878ED, "Grassroots Drifter")
    AddTextEntryByHash(0x4F26753A, "Plastic Cutout Ducktail")
    AddTextEntryByHash(0x4F600363, "LSCM Special")
    AddTextEntryByHash(0x4FB40029, "Carbon Race Splitter")
    AddTextEntryByHash(0x5A8A3004, "Sec. Rally Scoop w/ Aerial")
    AddTextEntryByHash(0x5A96CF7C, "Carbon Inset Skirts")
    AddTextEntryByHash(0x5AAEC322, "Black Strip")
    AddTextEntryByHash(0x5AB71AB7, "Full Radial Fairing")
    AddTextEntryByHash(0x5B5C370A, "Twin Exhaust")
    AddTextEntryByHash(0x5BCB702D, "Black Race w/ Sec. Trim")
    AddTextEntryByHash(0x5BF47D60, "Primary Sculpted Roof")
    AddTextEntryByHash(0x5C008D1C, "Secondary Wing Skirts")
    AddTextEntryByHash(0x5C76C421, "Winged Race w/ Sec. Trim Alt")
    AddTextEntryByHash(0x5CD468AD, "Tint 6")
    AddTextEntryByHash(0x5DB8EB87, "Race Diffuser")
    AddTextEntryByHash(0x5E315A37, "Hardy")
    AddTextEntryByHash(0x5EB239EB, "Dummy label.")
    AddTextEntryByHash(0x5F0237D3, "Secondary Tuner Wing")
    AddTextEntryByHash(0x5F9D7C7A, "Tuner Wing")
    AddTextEntryByHash(0x5F21E037, "Carbon Street Hood")
    AddTextEntryByHash(0x5F327D0E, "Oval Exhaust")
    AddTextEntryByHash(0x5F154991, "Carbon Rake Splitter")
    AddTextEntryByHash(0x5FC37CBF, "Lip Spoiler w/ Roof Spoiler")
    AddTextEntryByHash(0x6A3FB9C8, "Cut Off Radial Fairing")
    AddTextEntryByHash(0x6AF9E15A, "Secondary Rake Splitter")
    AddTextEntryByHash(0x6AFF8507, "Tint 7")
    AddTextEntryByHash(0x6B87F800, "Santa Skull Track Pants")
    AddTextEntryByHash(0x6C44E5F8, "Accented Special Stripes Black")
    AddTextEntryByHash(0x6C52D274, "Plastic Tuner Wing")
    AddTextEntryByHash(0x6C61D60D, "Atomic Racing Cap")
    AddTextEntryByHash(0x6C24799C, "Boar Support Frame")
    AddTextEntryByHash(0x6D72A4BC, "Higashi")
    AddTextEntryByHash(0x6D3997B2, "Drift Meet Wing")
    AddTextEntryByHash(0x6E7ECD93, "Primary Aero Hood")
    AddTextEntryByHash(0x6E7ED7FC, "Primary Stock Arches")
    AddTextEntryByHash(0x6E24AA68, "Grille w/ Plastic Slats")
    AddTextEntryByHash(0x6EA2304B, "Raised Wing")
    AddTextEntryByHash(0x6EF9D297, "Secondary Race Skirts")
    AddTextEntryByHash(0x6F0678B4, "Off-Road Guard Bumper")
    AddTextEntryByHash(0x6F4F6C1C, "STD Division Exhausts")
    AddTextEntryByHash(0x6F49C928, "Plastic Cowled Vented Hood")
    AddTextEntryByHash(0x6F983FF1, "Plastic Race Splitter")
    AddTextEntryByHash(0x6FDA0330, "Titanium Tipped Exhausts")
    AddTextEntryByHash(0x7A0D746C, "Titanium Exhaust")
    AddTextEntryByHash(0x7A4E1594, "Camo Jack Sheepe Track Pants")
    AddTextEntryByHash(0x7A8DEEEA, "Carbon Tuner Wing")
    AddTextEntryByHash(0x7A424B71, "Primary Ducktail Spoiler")
    AddTextEntryByHash(0x7A925A01, "LS Death Metal Shorts")
    AddTextEntryByHash(0x7A6864D7, "Blue Manor Hoodie")
    AddTextEntryByHash(0x7AD632B4, "Trim Spoiler")
    AddTextEntryByHash(0x7B1F2546, "Tint 4")
    AddTextEntryByHash(0x7B660D44, "Street Splitter")
    AddTextEntryByHash(0x7B34403F, "Kita")
    AddTextEntryByHash(0x7BAB3495, "Large Boot Lip Spoiler")
    AddTextEntryByHash(0x7BB91410, "Gray Jumping Spider Mask")
    AddTextEntryByHash(0x7BCC5F10, "Factory Black Stripe")
    AddTextEntryByHash(0x7BDEA3F8, "Plastic Skirt")
    AddTextEntryByHash(0x7BFB91E0, "Tuner Grille")
    AddTextEntryByHash(0x7C49D954, "Secondary Tuner Splitter")
    AddTextEntryByHash(0x7C76F5E9, "Plastic Splitter")
    AddTextEntryByHash(0x7CC7D215, "Razor Grille")
    AddTextEntryByHash(0x7CCB16F3, "THIS LABEL NEEDS TO BE HERE !!!")
    AddTextEntryByHash(0x7D33150D, "Robust Guard w/ Black Trim")
    AddTextEntryByHash(0x7DE98451, "Camo Jack Sheepe Cap")
    AddTextEntryByHash(0x7E45685B, "Secondary Aero Hood")
    AddTextEntryByHash(0x7EA704B4, "Titanium Tipped Exhausts")
    AddTextEntryByHash(0x7EB18163, "Secondary Triple Vent")
    AddTextEntryByHash(0x7EC3C4C8, "Dropped Skirt")
    AddTextEntryByHash(0x7F0A2C63, "Kabel Reflection")
    AddTextEntryByHash(0x7F1AEB48, "Vented Hood")
    AddTextEntryByHash(0x7F1F62A0, "HSW Splitter II")
    AddTextEntryByHash(0x7F2C525F, "Exposed Turbos Hood")
    AddTextEntryByHash(0x7F5FD380, "High Race Wing")
    AddTextEntryByHash(0x8A3184F8, "Plastic Custom Hood")
    AddTextEntryByHash(0x8C7D4CAC, "Secondary Competition Wing")
    AddTextEntryByHash(0x8C25DE4E, "Skirts w/ Big Fins")
    AddTextEntryByHash(0x8C70EFCE, "Plastic Ducktail Spoiler")
    AddTextEntryByHash(0x8C903B13, "Carbon Air Intake")
    AddTextEntryByHash(0x8C950ECD, "Chrome w/ Sec. Light Tape")
    AddTextEntryByHash(0x8C28948F, "Wide Stripe")
    AddTextEntryByHash(0x8C81890D, "LS Death Metal Hoodie")
    AddTextEntryByHash(0x8CB0054A, "Bosozoku Bumper")
    AddTextEntryByHash(0x8D780D37, "Police Bike")
    AddTextEntryByHash(0x8D980922, "Carbon Drift Kit")
    AddTextEntryByHash(0x8DAA6299, "Trim Dropped Skirt")
    AddTextEntryByHash(0x8E776F55, "Competition Ducktail")
    AddTextEntryByHash(0x8F4DC3E0, "Secondary Trim")
    AddTextEntryByHash(0x8F1976B8, "Plastic Razor Grille")
    AddTextEntryByHash(0x8FBF27FC, "Hands On Car Wash Cap")
    AddTextEntryByHash(0x8FC50F21, "Custom Flatbed")
    AddTextEntryByHash(0x8FCB9FE8, "Big Bore Exhaust")
    AddTextEntryByHash(0x9A3FE831, "Carbon Sports Wing")
    AddTextEntryByHash(0x9A6C7217, "Drift Meet Wing Alt.")
    AddTextEntryByHash(0x9A244EEF, "Robust Guard Bumper")
    AddTextEntryByHash(0x9A525697, "Secondary Air Intake")
    AddTextEntryByHash(0x9B5ED24E, "Bosozoku Hood")
    AddTextEntryByHash(0x9B13BDF3, "Small Radio Top Box")
    AddTextEntryByHash(0x9B31A7D7, "Sports Diffuser")
    AddTextEntryByHash(0x9B66E51C, "T-East Sports")
    AddTextEntryByHash(0x9B8205B6, "Kaido Hood")
    AddTextEntryByHash(0x9BAD1ECD, "Dynasty 8 Racing")
    AddTextEntryByHash(0x9BAE88F4, "Camo Jack Sheepe Track Pants")
    AddTextEntryByHash(0x9BD725A0, "Secondary Drift Kit")
    AddTextEntryByHash(0x9D6BA6C1, "Drift Bumper w/ Trim")
    AddTextEntryByHash(0x9D64E675, "Magnetics Bomber Zipped")
    AddTextEntryByHash(0x9E7BCA69, "Circuit Spec")
    AddTextEntryByHash(0x9E8ACAE1, "Secondary Strip")
    AddTextEntryByHash(0x9EAB3DA7, "Titanium Big Bore Exhaust")
    AddTextEntryByHash(0x9EBFB9BD, "Street Stripes")
    AddTextEntryByHash(0x9F7259D0, "Titanium Bore Exhaust")
    AddTextEntryByHash(0x9FD23F78, "Record Holder Red")
    AddTextEntryByHash(0x9FEE1502, "High Wing w/ Sec. Trim")
    AddTextEntryByHash(0x9FF78B4C, "Mildly Offended")
    AddTextEntryByHash(0x11BA3F07, "Performance Twin Intake Hood")
    AddTextEntryByHash(0x11DC8D25, "LSCM Electric Dragon")
    AddTextEntryByHash(0x12B38B8F, "Secondary Hood")
    AddTextEntryByHash(0x12C4788D, "Cutout Boot Lip Spoiler")
    AddTextEntryByHash(0x13EA889F, "HSW Competition Splitter")
    AddTextEntryByHash(0x14A244C1, "Lowrider Detailing")
    AddTextEntryByHash(0x14B83FA8, "Higgins Helitours Maverick")
    AddTextEntryByHash(0x14DCBC26, "Grille Reinforced")
    AddTextEntryByHash(0x15D686F5, "Battle Damaged")
    AddTextEntryByHash(0x16A2D8FB, "Atomic Racing Bomber Zipped")
    AddTextEntryByHash(0x16AF873C, "Something in Japanese")
    AddTextEntryByHash(0x18A9DA93, "Drift Enforcement")
    AddTextEntryByHash(0x18AC41E0, "Extended Splitter")
    AddTextEntryByHash(0x19C86322, "Ghosts Exposed Backwards Cap")
    AddTextEntryByHash(0x20EDAC71, "Carbon Twin Vented")
    AddTextEntryByHash(0x21C3A7EA, "HSW Front Bumper II")
    AddTextEntryByHash(0x21D600EC, "Street Wing")
    AddTextEntryByHash(0x22ACA623, "Trim Competition Splitter")
    AddTextEntryByHash(0x22BA36C4, "Buccaneer Hat")
    AddTextEntryByHash(0x22BB35A8, "Off-Road Bumper")
    AddTextEntryByHash(0x22F83325, "Tint 3")
    AddTextEntryByHash(0x24C0235D, "Wildstyle")
    AddTextEntryByHash(0x24D136B6, "Tuner Hood")
    AddTextEntryByHash(0x26CDE40D, "Carbon Tuner Splitter")
    AddTextEntryByHash(0x26D8E637, "Carbon Street Wing")
    AddTextEntryByHash(0x27ABEC08, "Tuner Fenders")
    AddTextEntryByHash(0x28FC5B78, "Suzume")
    AddTextEntryByHash(0x29B26DE8, "Secondary Vented Hood")
    AddTextEntryByHash(0x29B67CA0, "Jackal Racing")
    AddTextEntryByHash(0x32ED60D2, "Secondary Street Ducktail")
    AddTextEntryByHash(0x33F84E7C,
        "Any proud Walton owner will know the sublime feeling of superiority that comes from literally sitting above everyone else. But sometimes our relentless narcissism demands that we feel more centered, more grounded, closer to the people. Enter the L35 Stock: providing the same feeling of undisguised supremacy, but with suspension that minimizes your ground-clearance and maximizes your chances of getting that elusive up-skirt picture of your ex-wife's mindfulness coach without violating the terms of your restraining order.~n~~n~- Missile Lock-On Jammer available")
    AddTextEntryByHash(0x36A161A3, "Purple Jumping Spider Mask")
    AddTextEntryByHash(0x36C2096F, "Weekend Racer")
    AddTextEntryByHash(0x36C3338A, "Skirts w/ Fins")
    AddTextEntryByHash(0x36F5D9D7, "Drift Bumper")
    AddTextEntryByHash(0x37AD76BE, "Octagon Exhaust Tips")
    AddTextEntryByHash(0x37C656FD, "Full Course Yellow")
    AddTextEntryByHash(0x37EBE478, "Plastic Race Skirts")
    AddTextEntryByHash(0x37FA8B87, "Exposed Turbo")
    AddTextEntryByHash(0x38CD3B72, "Kurukuru")
    AddTextEntryByHash(0x38E668D6, "Yokohama Show Stopper")
    AddTextEntryByHash(0x39A61925, "Twin Vent Fenders")
    AddTextEntryByHash(0x40D16ED7, "Tint 4")
    AddTextEntryByHash(0x40E8FCCD, "Carbon Bolt-On Arches")
    AddTextEntryByHash(0x40E361CF, "Hardstand 300.5")
    AddTextEntryByHash(0x40F546B0, "Bobcat Security Stockade")
    AddTextEntryByHash(0x40F13842,
        "They say never to take work home with you, but what about taking 30,000lb of it at high speed into the carpool lane on the freeway? Sure, Bobcat Security have taken a calculated PR risk by franchising their brand to any sociopath with an urgent need to transport large amounts of cash, assets, or human captives at high speed in a built-up environment, but if that's not a case study in the financial value of moving fast and breaking things, we don't know what is.~n~~n~Please note: This is a Pegasus vehicle and cannot be stored in a personal garage.")
    AddTextEntryByHash(0x41BBC54C, "Plastic Competition Splitter")
    AddTextEntryByHash(0x43B0A209, "Off-Road Guard w/ Sec. Trim")
    AddTextEntryByHash(0x45B29563, "Chavos V6")
    AddTextEntryByHash(0x45D91E8C, "Race Grille")
    AddTextEntryByHash(0x45E4EB53, "Drift Skirts w/ Trim")
    AddTextEntryByHash(0x45EFD9FF, "Plastic w/ Chrome Slats")
    AddTextEntryByHash(0x46B8B199, "Red Yeti Fall Cap")
    AddTextEntryByHash(0x46B352DE, "Secondary Sculpted Roof")
    AddTextEntryByHash(0x46E96D64, "Mudguards")
    AddTextEntryByHash(0x47DB2AB5, "Carbon Hood")
    AddTextEntryByHash(0x48B67D58, "Performance Bumper")
    AddTextEntryByHash(0x48EC5082, "Carbon Wrapped Oval Exhaust")
    AddTextEntryByHash(0x50A962F7, "Plastic Finned Splitter")
    AddTextEntryByHash(0x50F4EB86, "Secondary Sport Bumper")
    AddTextEntryByHash(0x51E33E23, "R* Community Series Varsity")
    AddTextEntryByHash(0x52C5FAA7, "Tip Lip w/ Sec. Trim")
    AddTextEntryByHash(0x52D934FD, "Red Yeti Fall Cap")
    AddTextEntryByHash(0x52FB3E4B, "Horizontal Grille Slats")
    AddTextEntryByHash(0x53D3AF74, "Highway Patrol Kit")
    AddTextEntryByHash(0x54AE19F6, "Carbon Hood")
    AddTextEntryByHash(0x54C7970B, "Secondary Splitter")
    AddTextEntryByHash(0x55A10AD3, "Street Skirts")
    AddTextEntryByHash(0x55A34D66, "Hexagon Mesh Grille")
    AddTextEntryByHash(0x55B90FD4, "HSW Front Bumper I")
    AddTextEntryByHash(0x55FF9694, "Sec. Cowled Vented Hood")
    AddTextEntryByHash(0x56B2A9A4, "Plated")
    AddTextEntryByHash(0x56DED5E9, "Dominator FX")
    AddTextEntryByHash(0x56E50031, "Sec. Competition Ducktail")
    AddTextEntryByHash(0x57A7E8A6, "Sec. Hexagon Vented Trunk")
    AddTextEntryByHash(0x59D23592, "Drift Cage")
    AddTextEntryByHash(0x60A2177E, "Hands On Car Wash Cap")
    AddTextEntryByHash(0x60B8DC19, "Sports Guard w/ Sec. Trim")
    AddTextEntryByHash(0x60D44569, "Competition Vents")
    AddTextEntryByHash(0x60F8328A, "Plastic Hood")
    AddTextEntryByHash(0x61A7A7F2, "Sport Stripes White")
    AddTextEntryByHash(0x61A208BB, "Tuner Roof Scoop")
    AddTextEntryByHash(0x61BF0522, "Carbon Finned Splitter")
    AddTextEntryByHash(0x61FBFE2E, "HSW Sports Diffuser")
    AddTextEntryByHash(0x61FF646D, "Übermacht Hood")
    AddTextEntryByHash(0x63EBE226, "Secondary Inset Skirts")
    AddTextEntryByHash(0x63EDE9FB, "Chrome Mesh Grille")
    AddTextEntryByHash(0x65A6AD37, "Shaker Hood")
    AddTextEntryByHash(0x65DA6409, "Horizontal & Vertical Slats")
    AddTextEntryByHash(0x66AE7643, "Plastic Sunstrip")
    AddTextEntryByHash(0x68EB9D35, "GTS White Stripes")
    AddTextEntryByHash(0x68FB5379, "Rapid GT X")
    AddTextEntryByHash(0x70C68FDC, "Yogarishima Racing")
    AddTextEntryByHash(0x71B90505, "Rally Cage")
    AddTextEntryByHash(0x71F12105, "Boot Lip Spoiler")
    AddTextEntryByHash(0x72CF20E1, "Street Diffuser")
    AddTextEntryByHash(0x73B4BC1D, "Secondary Race Diffuser")
    AddTextEntryByHash(0x75DEBD55, "Santa Skull Track Pants")
    AddTextEntryByHash(0x76A1F797, "Hexagon Exhaust")
    AddTextEntryByHash(0x77E3E05D, "Carbon Custom Hood")
    AddTextEntryByHash(0x78A6BC9F, "GTS Black Stripes")
    AddTextEntryByHash(0x79A13486, "Red Yeti Fall Cap")
    AddTextEntryByHash(0x80C1FC82, "Secondary Stock Arches")
    AddTextEntryByHash(0x81F1CE4F, "Secondary Badged Wing Vent")
    AddTextEntryByHash(0x82D00727, "Padded Full Roll Cage")
    AddTextEntryByHash(0x84DAA56E, "Race Hood")
    AddTextEntryByHash(0x85C4F8C1, "Tint 8")
    AddTextEntryByHash(0x85C52676, "Bore Exhaust")
    AddTextEntryByHash(0x86BBEEFF, "Carbon Split Race Splitter")
    AddTextEntryByHash(0x87B05E1F, "Cowled Vented Hood")
    AddTextEntryByHash(0x87E646F6, "Primary Stock Mirrors")
    AddTextEntryByHash(0x87F08CA5, "Carbon Mirrors")
    AddTextEntryByHash(0x87F82E06, "Carbon w/ Sec. Trim Diffuser")
    AddTextEntryByHash(0x88BBD8AD, "Chassis Mounted Wing")
    AddTextEntryByHash(0x88D030B3, "Blue Manor Hoodie")
    AddTextEntryByHash(0x88D1196E, "Extended Radio Top Box")
    AddTextEntryByHash(0x88F0772D, "Cruiser Fairing w/ Big Screen")
    AddTextEntryByHash(0x89BF6899, "Wing Skirts w/ Sec. Trim")
    AddTextEntryByHash(0x89D676A1, "Drift Walton L35")
    AddTextEntryByHash(0x90FF25FE, "Carbon Triple Vent")
    AddTextEntryByHash(0x91C90519, "Split Race Splitter")
    AddTextEntryByHash(0x91ED7572, "Magnetics Track Pants")
    AddTextEntryByHash(0x91FDDF4A, "Tuner w/ Large Fins & Canards")
    AddTextEntryByHash(0x92DBEB2E, "Competition Roof Scoop")
    AddTextEntryByHash(0x93B15777, "Street Diffuser")
    AddTextEntryByHash(0x94A2E4EC, "Drift Wing")
    AddTextEntryByHash(0x94AAC9C3, "Carbon Vented Hood")
    AddTextEntryByHash(0x95A3916D, "Carbon Vented Hood")
    AddTextEntryByHash(0x95FC0E51, "Extended Chin Guard Splitter")
    AddTextEntryByHash(0x95FEAB0E, "Standard Issue Top Box")
    AddTextEntryByHash(0x96CA2337, "Secondary w/ Light Tape")
    AddTextEntryByHash(0x97D1BD15, "Accented Special Stripes Red")
    AddTextEntryByHash(0x98C42C82, "Street Ducktail")
    AddTextEntryByHash(0x98EA9DA9, "Plastic Vented Hood")
    AddTextEntryByHash(0x98F9F934, "Carbon Dropped Skirt")
    AddTextEntryByHash(0x99F33B4C, "Carb. Wrapped Chrome Exhausts")
    AddTextEntryByHash(0x99F93E45, "Triple Exhaust")
    AddTextEntryByHash(0x121B02DF, "Gray Space Interloper")
    AddTextEntryByHash(0x125F9960, "Carbon Race Skirts")
    AddTextEntryByHash(0x144F865B, "Secondary Trim Diffuser")
    AddTextEntryByHash(0x146A6000, "Secondary Street Mirrors")
    AddTextEntryByHash(0x152F42E4, "Street Wing")
    AddTextEntryByHash(0x167F474E, "Tip Lip Skirts")
    AddTextEntryByHash(0x210B9AED, "Everon RS")
    AddTextEntryByHash(0x218F22A8, "Drift Skirts")
    AddTextEntryByHash(0x240AECFD, "Winged Race Splitter")
    AddTextEntryByHash(0x248B1E32, "Secondary Tip Lip Skirts")
    AddTextEntryByHash(0x251D84BD, "HSW Ducktail III")
    AddTextEntryByHash(0x265B21D2, "Carbon High Wing Skirts")
    AddTextEntryByHash(0x285DC51C, "Gray Jumping Spider Mask")
    AddTextEntryByHash(0x288E9721, "Extended Skirts")
    AddTextEntryByHash(0x297BCF37, "Hot Pink")
    AddTextEntryByHash(0x316D43A4, "Sec. Competition Splitter")
    AddTextEntryByHash(0x323D1D19, "Race w/ Black Trim")
    AddTextEntryByHash(0x340E22A2, "HSW Ducktail II")
    AddTextEntryByHash(0x347E3A48, "Carbon Tuner Ducktail")
    AddTextEntryByHash(0x369E07E4, "Off-Road Guard w/ Black Trim")
    AddTextEntryByHash(0x390D6B99, "Smoke on the Water Hoodie")
    AddTextEntryByHash(0x415DBB52, "Competition w/ Black Trim")
    AddTextEntryByHash(0x418E7030, "Dewbauchee Hood")
    AddTextEntryByHash(0x445A8C76, "Carbon Competition Vents")
    AddTextEntryByHash(0x450C8658, "Half Coat")
    AddTextEntryByHash(0x487D343F, "Larger Bore Exhausts")
    AddTextEntryByHash(0x487E5D04, "Street Wing")
    AddTextEntryByHash(0x490DD43C, "HSW Bumper I")
    AddTextEntryByHash(0x500FC952, "Dense Motorsport")
    AddTextEntryByHash(0x535A791C, "Carbon Race Ducktail")
    AddTextEntryByHash(0x547F3432, "Primary Large Splitter")
    AddTextEntryByHash(0x549E17F0, "Torpedo Wing Mounted Mirrors")
    AddTextEntryByHash(0x557FA3B2, "Secondary Trunk Wing")
    AddTextEntryByHash(0x559EC728, "Pro Stock")
    AddTextEntryByHash(0x567E06C4, "Clipping Point")
    AddTextEntryByHash(0x573B7097, "HSW Bumper II")
    AddTextEntryByHash(0x578F90A7, "Bolt-On MK II Splitter")
    AddTextEntryByHash(0x580F5C5A, "Winged Skirt")
    AddTextEntryByHash(0x581E1D74, "Tint 7")
    AddTextEntryByHash(0x603FAD92, "Raised Hood")
    AddTextEntryByHash(0x606A0EF3, "Grille w/ Slats")
    AddTextEntryByHash(0x624CB34D, "Race Wing Mounted Mirrors")
    AddTextEntryByHash(0x627ED7D7, "Crossbar Grille")
    AddTextEntryByHash(0x628C00BF, "Carbon Drift Wing")
    AddTextEntryByHash(0x635E2181, "Red Yeti Fall Cap")
    AddTextEntryByHash(0x645B530A, "Chrome Exhaust")
    AddTextEntryByHash(0x665E0403, "Art Projekt")
    AddTextEntryByHash(0x674CEA84, "Weekday Racer")
    AddTextEntryByHash(0x690ED26F, "Chrome Exhaust")
    AddTextEntryByHash(0x696CB094, "Primary Trim w/ Race Diffuser")
    AddTextEntryByHash(0x697B347E, "Bolt-On MK II w/ Sec. Trim")
    AddTextEntryByHash(0x697EEB82, "Chassis Mounted Wing")
    AddTextEntryByHash(0x706CDD18, "Shota")
    AddTextEntryByHash(0x721EAB82, "Carbon Race Skirt")
    AddTextEntryByHash(0x726B64A7, "Spy Shots")
    AddTextEntryByHash(0x728A68D5, "Secondary Competition Vents")
    AddTextEntryByHash(0x732C8145, "Carbon Exhaust V2")
    AddTextEntryByHash(0x740F14B4, "Race Wing")
    AddTextEntryByHash(0x743B49FE, "Secondary Bolt-On MK II")
    AddTextEntryByHash(0x765ACCC5, "Taxi Import")
    AddTextEntryByHash(0x803DC419, "Alternate Dual Exhaust")
    AddTextEntryByHash(0x805CA699, "Single Vent Fenders")
    AddTextEntryByHash(0x837A023A, "Street Twin Power Hood")
    AddTextEntryByHash(0x843B4FBB, "Secondary Dropped Skirt")
    AddTextEntryByHash(0x852C97CB, "Tarmac Spec")
    AddTextEntryByHash(0x856B4983, "Carbon Wrapped Chrome Exhaust")
    AddTextEntryByHash(0x856EECFE, "HSW Race Splitter")
    AddTextEntryByHash(0x864C965F, "Black Sport Grille")
    AddTextEntryByHash(0x866C2D46, "Tuner Hood")
    AddTextEntryByHash(0x884B6CF4, "Zigzag Shakotan Exhausts")
    AddTextEntryByHash(0x891C4087, "Sakura")
    AddTextEntryByHash(0x913C7C08, "HSW Mirrors I")
    AddTextEntryByHash(0x935A24A4, "Cyber Graphics")
    AddTextEntryByHash(0x948D32E0, "Chrome Sport Grille")
    AddTextEntryByHash(0x962A2918, "HSW Mirrors")
    AddTextEntryByHash(0x963BCA8D, "Competition Diffuser")
    AddTextEntryByHash(0x968EE673, "Pulse Vented Trunk")
    AddTextEntryByHash(0x973F5AB9, "Primary Stock")
    AddTextEntryByHash(0x983FD8E4, "Tint 2")
    AddTextEntryByHash(0x987DCCE5, "White Stripes")
    AddTextEntryByHash(0x997F0600, "STD Division Spoiler")
    AddTextEntryByHash(0x1330FB64, "Camo Jack Sheepe Cap")
    AddTextEntryByHash(0x1531E197, "Secondary Sport Mirrors")
    AddTextEntryByHash(0x1794D85D, "Team Hardstand")
    AddTextEntryByHash(0x1813FD69, "Fuel Cell")
    AddTextEntryByHash(0x2166F6D3, "GT Mirrors")
    AddTextEntryByHash(0x2488D479, "Carbon Splitter")
    AddTextEntryByHash(0x2592B296, "GT Graphics")
    AddTextEntryByHash(0x2634EC65, "Higgins Helitours Tee")
    AddTextEntryByHash(0x2735FAF7, "Street Ducktail")
    AddTextEntryByHash(0x2858A938, "Plastic w/ Chrome Razor")
    AddTextEntryByHash(0x3019BB7B, "Dinka Delivery")
    AddTextEntryByHash(0x3040AAEA, "Plastic Badged Wing Vent")
    AddTextEntryByHash(0x3062A63D, "Secondary Roof")
    AddTextEntryByHash(0x3413A9CC, "Sec. Trimmed Finned Splitter")
    AddTextEntryByHash(0x3534A7A2, "Ducktail w/ Roof Spoiler")
    AddTextEntryByHash(0x3790DC96, "Carbon Skirted Splitter")
    AddTextEntryByHash(0x3797BD4F, "Plastic Slender Vertical")
    AddTextEntryByHash(0x3897EE24, "Sec. Trimmed Street Splitter")
    AddTextEntryByHash(0x4116D749, "Wing Skirts")
    AddTextEntryByHash(0x4643A872, "Racing Stripes")
    AddTextEntryByHash(0x4702AEB6, "Camo Jack Sheepe Cap")
    AddTextEntryByHash(0x5073CFEC, "Tint 9")
    AddTextEntryByHash(0x5098BF48, "Utility Diffuser")
    AddTextEntryByHash(0x5158DFF1, "Medium Boot Lip Spoiler")
    AddTextEntryByHash(0x5330F481, "Plastic w/ Secondary Slats")
    AddTextEntryByHash(0x5383C3CF, "Vented Fenders")
    AddTextEntryByHash(0x5548B20B, "Atomic Racing Cap")
    AddTextEntryByHash(0x5609C8B2, "Brown Jumping Spider Mask")
    AddTextEntryByHash(0x5813B3E8, "Mix Competition Vents")
    AddTextEntryByHash(0x5827CEE9, "HSW Twin Intake Hood")
    AddTextEntryByHash(0x5959CE6D, "Twin Intake Hood")
    AddTextEntryByHash(0x6377E8F7, "Alternative Badge Grille")
    AddTextEntryByHash(0x6398B302, "Carbon Aero Hood")
    AddTextEntryByHash(0x6492D0F2, "Traffic Enforcement Kit")
    AddTextEntryByHash(0x6637E76E, "Secondary Race Hood")
    AddTextEntryByHash(0x6661EE57, "Padded Rally Cage")
    AddTextEntryByHash(0x6708DB80, "Accented Special Stripes White")
    AddTextEntryByHash(0x6923A4AE, "Plastic Race Ducktail")
    AddTextEntryByHash(0x7109D45C, "Left Mounted Front Plate")
    AddTextEntryByHash(0x7275B049, "Leicht")
    AddTextEntryByHash(0x7360BF47, "Plastic w/ Secondary Hawk")
    AddTextEntryByHash(0x7397FA09, "Plastic Race Grille")
    AddTextEntryByHash(0x7861AF70, "Titanium Tipped Exhaust")
    AddTextEntryByHash(0x8542A74C, "Race Fenders")
    AddTextEntryByHash(0x8974C1F1, "Tint 5")
    AddTextEntryByHash(0x9034B342, "Plastic Crossbar Grille")
    AddTextEntryByHash(0x9468AA62, "Rear Mudguards")
    AddTextEntryByHash(0x9508F8D0, "Cowled Hood")
    AddTextEntryByHash(0x9608A757, "Everon Street SC")
    AddTextEntryByHash(0x9910CD15, "Titanium Exhaust V2")
    AddTextEntryByHash(0x10040D1E, "Carbon Heavy Duty Diffuser")
    AddTextEntryByHash(0x10953FA6, "Curved Medium Mudguard")
    AddTextEntryByHash(0x24503D41, "Primary Race Skirts")
    AddTextEntryByHash(0x27329C85, "Slender Vertical Grille")
    AddTextEntryByHash(0x28842FB1, "The Slasher Clown")
    AddTextEntryByHash(0x29106E20,
        "You'd probably be forgiven if you didn't immediately think \"terrifying drift machine\" when you saw this no-frills compact pick-up truck. There is no such thing as forgiveness, however, when some gibbering drift-nerd hits you with the driver-side door at 200mph on your roadside hike through Great Chaparral. But then, that particular douchebag saw the potential for a perfectly balanced jumble of physics-defying performance modifications that might, on a good day, not quite tear the chassis apart - and you didn't. So, lesson learned.~n~~n~- Missile Lock-On Jammer available~n~- Drift tuning built in (non-customizable)~n~~n~Please note: LS Car Meet Membership required for access to drift races.")
    AddTextEntryByHash(0x37044BC4, "Primary Trim Diffuser")
    AddTextEntryByHash(0x37514E2C, "Drift Skirts MK II")
    AddTextEntryByHash(0x41750AB7, "Cruiser Top Box")
    AddTextEntryByHash(0x45372F49, "Sports Guard w/ Black Trim")
    AddTextEntryByHash(0x45557B41, "Primary Custom Hood")
    AddTextEntryByHash(0x45824CA9, "Secondary Race Splitter")
    AddTextEntryByHash(0x50868CDE, "Plastic Aero Hood")
    AddTextEntryByHash(0x52785D87, "Competition Bumper")
    AddTextEntryByHash(0x55094C1A, "Crossbar Grille")
    AddTextEntryByHash(0x55471ECA, "Roll Cage")
    AddTextEntryByHash(0x57848B67, "Love Shakotan Exhausts")
    AddTextEntryByHash(0x59236AE5, "Black Rear w/ Black Trim")
    AddTextEntryByHash(0x59295B39, "Primary Sunstrip")
    AddTextEntryByHash(0x63568E78, "Ghosts Exposed Forwards Cap")
    AddTextEntryByHash(0x63771BA2, "Race Diffuser w/ Sec. Trim")
    AddTextEntryByHash(0x66404E08, "Half Roll Cage")
    AddTextEntryByHash(0x68950C6D, "Tuner Diffuser")
    AddTextEntryByHash(0x69633F11,
        "If you want to get as close to driving a people carrier as you can without completely giving up your hopes of ever having extramarital sex again, then boy oh boy is this the car for you. Equally equipped to chaperone little Tristan to his therapy session as it is to nimbly outmaneuver the LSPD as you violate 14 traffic laws en route to your next Hush Smush date, vehicular multitasking has never felt so 21st century.~n~~n~- Missile Lock-On Jammer available")
    AddTextEntryByHash(0x69850D8E, "Plastic Sunstrip")
    AddTextEntryByHash(0x78362C13, "Bosozoku Wing")
    AddTextEntryByHash(0x84122DD9, "R* Community Series Varsity")
    AddTextEntryByHash(0x85036EA9, "Touring Stripes Blue")
    AddTextEntryByHash(0x85254FC1, "Classic Surf Board")
    AddTextEntryByHash(0x88816AD6, "Korean Import")
    AddTextEntryByHash(0x92197E04, "Santa Skull Sweater")
    AddTextEntryByHash(0x93914BFC, "Sports Guard Bumper")
    AddTextEntryByHash(0x95835EBC, "Secondary Sports Wing")
    AddTextEntryByHash(0x96187CE1, "HSW Racing")
    AddTextEntryByHash(0x99078EBA, "Pluck Me Sweater")
    AddTextEntryByHash(0x126826BF, "Drift Bumper")
    AddTextEntryByHash(0x153225AC, "Everon - Super Special")
    AddTextEntryByHash(0x212314AE, "Tuner Ducktail")
    AddTextEntryByHash(0x263466E9, "Rugged Rack Roof Basket")
    AddTextEntryByHash(0x293215F3, "Walton L35 Stock")
    AddTextEntryByHash(0x316084E1, "Horizontal Grille")
    AddTextEntryByHash(0x332772E8, "Red On The Pisswasser Tee")
    AddTextEntryByHash(0x354323DD, "Carbon Pulse Vented Trunk")
    AddTextEntryByHash(0x367641AE, "Sec. Carb. GT MK II Wing")
    AddTextEntryByHash(0x429062DC, "Sec. Trim w/ Race Diffuser")
    AddTextEntryByHash(0x516344BA, "Air Intake Hood")
    AddTextEntryByHash(0x535695F4, "Large Straight Up Pipes")
    AddTextEntryByHash(0x576790B9, "Secondary Shaker Hood")
    AddTextEntryByHash(0x591210D4, "The Buccaneer")
    AddTextEntryByHash(0x622782FC, "Carbon Wrapped Exhaust")
    AddTextEntryByHash(0x622835C1, "Race Diffuser")
    AddTextEntryByHash(0x641240D7, "Plastic Trunk Wing")
    AddTextEntryByHash(0x703481BC, "Boar Support Frame Plus")
    AddTextEntryByHash(0x703500D8, "Street Hood")
    AddTextEntryByHash(0x717631AB, "Vented Hood")
    AddTextEntryByHash(0x719664B4, "Full Roll Cage")
    AddTextEntryByHash(0x760540BE, "Carbon Diffuser")
    AddTextEntryByHash(0x850089D1, "Backside Autosport")
    AddTextEntryByHash(0x876389C1, "Carbon Ducktail")
    AddTextEntryByHash(0x914284E2, "Sport Bumper")
    AddTextEntryByHash(0x1145769F, "Carbon Clean Hood")
    AddTextEntryByHash(0x1293923B, "Street Hood")
    AddTextEntryByHash(0x1348861B, "Street Skirts MK II")
    AddTextEntryByHash(0x2209014B, "Lip Spoiler")
    AddTextEntryByHash(0x2344810F, "HSW Ducktail I")
    AddTextEntryByHash(0x3233936C, "Tint 8")
    AddTextEntryByHash(0x3618072F, "Secondary Hood")
    AddTextEntryByHash(0x4563783B, "Secondary Skirted Splitter")
    AddTextEntryByHash(0x4914959E, "Mosh Mosh")
    AddTextEntryByHash(0x5105021A, "Bayshore Racer")
    AddTextEntryByHash(0x6396226F, "Team Pole Position")
    AddTextEntryByHash(0x8114396F, "QuickiePharm")
    AddTextEntryByHash(0x9964217B, "Round Alternate Mirrors")
    AddTextEntryByHash(0x10799125, "Off-Road w/ Black Trim")
    AddTextEntryByHash(0x10860551, "Part of Money Fronts")
    AddTextEntryByHash(0x29684531, "Modern Surf Board")
    AddTextEntryByHash(0x30920469, "Titanium Tipped Large Bore")
    AddTextEntryByHash(0x36067774, "Secondary Splitter")
    AddTextEntryByHash(0x48446490, "Carb. Exposed Turbos Hood")
    AddTextEntryByHash(0x54494391, "Race Hood")
    AddTextEntryByHash(0x58112286, "Übermacht Roof Box")
    AddTextEntryByHash(0x59982579, "Right Mounted Front Plate")
    AddTextEntryByHash(0x62753266, "Extended Splitter")
    AddTextEntryByHash(0x64282860, "Gallantry Spec")
    AddTextEntryByHash(0x64712062, "Basic Panniers")
    AddTextEntryByHash(0x75397001, "Woodlander")
    AddTextEntryByHash(0x76964247, "High Wing Skirts")
    AddTextEntryByHash(0x77048695, "Carbon Wing")
    AddTextEntryByHash(0x90470277, "Vented Hood")
    AddTextEntryByHash(0x97819014, "Primary Windscreen")
    AddTextEntryByHash(0xA1C5F021, "Sports Wing")
    AddTextEntryByHash(0xA1CA9ED7, "Meinmacht Racing")
    AddTextEntryByHash(0xA1CE4D62, "Chrome Hexagon Mesh")
    AddTextEntryByHash(0xA1DE5126, "Urban Fighter")
    AddTextEntryByHash(0xA2A0A6C8, "Split Race w/ Sec. Trim")
    AddTextEntryByHash(0xA4A4EE8E, "Primary Trim")
    AddTextEntryByHash(0xA5B9B71E,
        "With the Woodlander you get to bring the rustic vibes of Paleto Forest on your journey, no matter where you're headed. Be it racing to your talent agent's office in Downtown before it's midday and they're too drunk to function, or crushing amphetamines to prepare for your seventh Vinewood audition of the morning, you can wind down your window, breathe in deeply, and smell the crisp pine, the musty earth, and the carcass of the coyote you flattened 5 miles back.~n~~n~- Missile Lock-On Jammer available")
    AddTextEntryByHash(0xA5D9FABB, "Tint 2")
    AddTextEntryByHash(0xA5E40906, "Competition Wing")
    AddTextEntryByHash(0xA5F83363, "Multi-Stripes")
    AddTextEntryByHash(0xA5FBC5C9, "Carbon Arm Race Wing")
    AddTextEntryByHash(0xA6F11E96, "HSW Racing")
    AddTextEntryByHash(0xA6F5366C, "Dummy label.")
    AddTextEntryByHash(0xA7CDA29D, "Small Profile Wing")
    AddTextEntryByHash(0xA8A31BB1, "Primary Wing Vent")
    AddTextEntryByHash(0xA8AA67CC, "Plastic Basic Splitter")
    AddTextEntryByHash(0xA8AD050B, "Race Wing")
    AddTextEntryByHash(0xA8E93DA6, "Carbon Vented Hood")
    AddTextEntryByHash(0xA9AE5EC6, "Secondary Rally Splitter")
    AddTextEntryByHash(0xA9BC9D14, "Carbon Sports Tuner Bumper")
    AddTextEntryByHash(0xA12CDCA7, "Inset Skirts")
    AddTextEntryByHash(0xA15E951F, "Secondary Race Ducktail")
    AddTextEntryByHash(0xA17C88F3, "Sentinel GTS")
    AddTextEntryByHash(0xA20DBCE5, "Race Wing")
    AddTextEntryByHash(0xA46F253B, "Superstar Shakotan Exhaust")
    AddTextEntryByHash(0xA58D6E96, "Small Pipe Exhausts")
    AddTextEntryByHash(0xA80AF208, "Single Filter Blower")
    AddTextEntryByHash(0xA82BCB9D, "Street Plain Hood")
    AddTextEntryByHash(0xA86F4252, "Trim Race Diffuser")
    AddTextEntryByHash(0xA90AE024, "Street Exhaust")
    AddTextEntryByHash(0xA92EFE98, "Skirt w/ Primary Trim")
    AddTextEntryByHash(0xA99A7B99, "Tint 1")
    AddTextEntryByHash(0xA405E621, "Plastic Competition Diffuser")
    AddTextEntryByHash(0xA480BAD5, "Standard Issue Panniers")
    AddTextEntryByHash(0xA607CDA0, "Sport Bumper")
    AddTextEntryByHash(0xA654E866, "HSW Heat Extractor")
    AddTextEntryByHash(0xA851FF36, "Secondary Mirrors")
    AddTextEntryByHash(0xA4676EAE, "Secondary Fenders")
    AddTextEntryByHash(0xA7076D21, "LS Death Metal Hoodie")
    AddTextEntryByHash(0xA7242F10, "Carbon Competition Splitter")
    AddTextEntryByHash(0xA84730C1, "Haiso Black")
    AddTextEntryByHash(0xA617546C, "Tampa GT")
    AddTextEntryByHash(0xA3013925, "Smoke on the Water Hoodie")
    AddTextEntryByHash(0xA5925657, "Large Splitter w/ Sec. Trim")
    AddTextEntryByHash(0xAA18D128, "Secondary Street Splitter")
    AddTextEntryByHash(0xAB6CF377, "Purple Jumping Spider Mask")
    AddTextEntryByHash(0xAB58FFEF, "Red Line")
    AddTextEntryByHash(0xAB98F31B, "Black Stripes")
    AddTextEntryByHash(0xABA192E9, "Carbon Muscle Killer Wing")
    AddTextEntryByHash(0xABE29671, "Chrome Exhaust")
    AddTextEntryByHash(0xAC8FDD1F, "Triple Vent")
    AddTextEntryByHash(0xAC9C1CC9, "Angled Exhaust")
    AddTextEntryByHash(0xAC19BA1B, "LSCM x Yeti")
    AddTextEntryByHash(0xAC41DFE9, "Chrome Exhausts")
    AddTextEntryByHash(0xAC60D912, "Angled Blast Pipes")
    AddTextEntryByHash(0xACD8549F, "Carbon Rally Scoop")
    AddTextEntryByHash(0xAD4BD6D5, "Double Stripes")
    AddTextEntryByHash(0xAD9287BA, "Secondary Street Ducktail")
    AddTextEntryByHash(0xADB02F76, "Carbon Cowl Induction Hood")
    AddTextEntryByHash(0xAE37FE61, "Carbon Extended Skirts")
    AddTextEntryByHash(0xAEB275C0, "Silver Mesh Grille")
    AddTextEntryByHash(0xAF154CDD, "Square Alternate Mirrors")
    AddTextEntryByHash(0xAF194382, "Cruiser Fairing")
    AddTextEntryByHash(0xAFB9E939, "Secondary Sport Grille")
    AddTextEntryByHash(0xAFF3E7B3, "Patrol Top Box")
    AddTextEntryByHash(0xAFF52B47, "Cel Shaded")
    AddTextEntryByHash(0xB1B4388E, "Secondary High Wing Skirts")
    AddTextEntryByHash(0xB2A8F2BB, "Karin Performance White")
    AddTextEntryByHash(0xB2D883C6, "Carbon Competition Diffuser")
    AddTextEntryByHash(0xB3D4F2DC, "Race Splitter")
    AddTextEntryByHash(0xB3D55242, "Carbon Cowled Vented")
    AddTextEntryByHash(0xB4B230A8, "Secondary Race Skirt")
    AddTextEntryByHash(0xB4F4452A, "Well Worn")
    AddTextEntryByHash(0xB5E60DBE, "Dual Filter Blower")
    AddTextEntryByHash(0xB5F1D7B7, "Vented Hood")
    AddTextEntryByHash(0xB6BE8DA9, "Ridged Grille")
    AddTextEntryByHash(0xB6EAA186, "Carbon Competition Wing")
    AddTextEntryByHash(0xB8D56EF5, "I Survived Cayo Perico Tee")
    AddTextEntryByHash(0xB9CB80C3, "TINT")
    AddTextEntryByHash(0xB9D25846, "Touring Stripes Yellow")
    AddTextEntryByHash(0xB9E6700A, "Rounded Double Stripes")
    AddTextEntryByHash(0xB9F8D424, "Haiso White")
    AddTextEntryByHash(0xB14FFE30, "V8 Swap")
    AddTextEntryByHash(0xB21F3F80, "Indiana Champ")
    AddTextEntryByHash(0xB26E8D45, "Tint 6")
    AddTextEntryByHash(0xB32E5830, "Lightweight Panniers")
    AddTextEntryByHash(0xB33B5F40, "Carbon Street Wing")
    AddTextEntryByHash(0xB35B490F, "Secondary Sport Lip Splitter")
    AddTextEntryByHash(0xB38A317F, "Badged Wing Vent")
    AddTextEntryByHash(0xB44E9FC6, "Carbon Street Mirrors")
    AddTextEntryByHash(0xB51B7499, "Titanium Tipped Exhausts")
    AddTextEntryByHash(0xB65D6800, "Everon Street Hood")
    AddTextEntryByHash(0xB83EADBB, "Race Wing")
    AddTextEntryByHash(0xB141FD6F, "Primary Hexagon Exhaust")
    AddTextEntryByHash(0xB238D1EC, "Large Splitter")
    AddTextEntryByHash(0xB486B2A8, "HSW Sports Tuner Bumper")
    AddTextEntryByHash(0xB671CDAB, "Competition Splitter")
    AddTextEntryByHash(0xB782DC21, "Plastic Utility Diffuser")
    AddTextEntryByHash(0xB29264F8, "Record Holder Blue")
    AddTextEntryByHash(0xB2928437, "Camo Jack Sheepe Hoodie")
    AddTextEntryByHash(0xB4191739, "Tint 3")
    AddTextEntryByHash(0xB8386922, "Carbon Race Wing")
    AddTextEntryByHash(0xB8876790, "Ghosts Exposed Forwards Cap")
    AddTextEntryByHash(0xBA1D6F55, "Secondary Rally Scoop")
    AddTextEntryByHash(0xBA7E2D7A, "TINT")
    AddTextEntryByHash(0xBA62EA68, "Chrome w/ Light Tape")
    AddTextEntryByHash(0xBAD1B934, "Single Exhaust")
    AddTextEntryByHash(0xBB3A0466, "Titanium Exhaust")
    AddTextEntryByHash(0xBB3BAA7A, "Tuner Mirrors")
    AddTextEntryByHash(0xBB5D5D4E, "Boar Bash Bar Plus")
    AddTextEntryByHash(0xBB6A1BB5, "Chrome Extended Splitter")
    AddTextEntryByHash(0xBB144FEF, "Arrow Racing")
    AddTextEntryByHash(0xBB7216B8, "Plastic Slender Grille")
    AddTextEntryByHash(0xBBD644FB, "Street Ready Pack V2")
    AddTextEntryByHash(0xBBF6126E, "Modern Surf Board")
    AddTextEntryByHash(0xBC829AF6, "Plastic Extended Skirts")
    AddTextEntryByHash(0xBC429441, "Secondary Race Hood")
    AddTextEntryByHash(0xBCABC809, "Performance Intake Hood")
    AddTextEntryByHash(0xBDEB5089, "Carbon Race Diffuser")
    AddTextEntryByHash(0xBDFFF6F5, "Custom Ducktail")
    AddTextEntryByHash(0xBE07CF15, "Cutout Stock Spoiler")
    AddTextEntryByHash(0xBE3ECF7F, "Small Wing")
    AddTextEntryByHash(0xBE5E70B6, "Minimus")
    AddTextEntryByHash(0xBE38753A, "Plastic Race Wing")
    AddTextEntryByHash(0xBEDA6F28, "Secondary Race Diffuser")
    AddTextEntryByHash(0xBF0A7903, "Carbon Rally Scoop w/ Aerial")
    AddTextEntryByHash(0xBF6F0C4F, "Karin Performance")
    AddTextEntryByHash(0xC073F11B, "Heavy Duty Bumper")
    AddTextEntryByHash(0xC075F28D, "Gray Space Interloper")
    AddTextEntryByHash(0xC0946385, "Aero Splitter")
    AddTextEntryByHash(0xC1DD758E, "High Capacity Panniers")
    AddTextEntryByHash(0xC2AD1DE1, "Tuner Wing")
    AddTextEntryByHash(0xC4C0D4DE, "Leicht Mono")
    AddTextEntryByHash(0xC6C3D4CB, "Trim Race Skirt")
    AddTextEntryByHash(0xC6C814F5, "Double Small Bore Exhausts")
    AddTextEntryByHash(0xC7A0D4B7, "Clean w/ Roof Spoiler")
    AddTextEntryByHash(0xC8A4EB10, "Retro Detailing")
    AddTextEntryByHash(0xC8E79D05, "Splitter w/ Secondary Trim")
    AddTextEntryByHash(0xC9FA97F4, "Secondary Sport Vented Hood")
    AddTextEntryByHash(0xC12FBE05, "Extreme Downforce BGW")
    AddTextEntryByHash(0xC22E3B85, "Primary Sport Mirrors")
    AddTextEntryByHash(0xC37FE7C7, "Trim Race Splitter")
    AddTextEntryByHash(0xC44CEAF2, "Chin Guard Splitter")
    AddTextEntryByHash(0xC56D13E5, "Squadron")
    AddTextEntryByHash(0xC57C5493, "Secondary Tuner Bumper")
    AddTextEntryByHash(0xC63BE4F8, "Plastic w/ Secondary Razor")
    AddTextEntryByHash(0xC64CB92E, "Secondary Race Wing")
    AddTextEntryByHash(0xC68F16E3, "Chrome Wire Mesh Grille")
    AddTextEntryByHash(0xC69B0DE6, "Slashed Blast Pipes")
    AddTextEntryByHash(0xC95C6C43, "HSW Mirrors II")
    AddTextEntryByHash(0xC416B453, "Stock w/ Secondary Trim")
    AddTextEntryByHash(0xC551B1B5, "TINT")
    AddTextEntryByHash(0xC912D5B6, "Straight Dual Exhaust")
    AddTextEntryByHash(0xC914B255, "Plastic Ridged Grille")
    AddTextEntryByHash(0xC1482AF8, "Tint 5")
    AddTextEntryByHash(0xC3445B50, "Sec. Carb. Downforce BGW")
    AddTextEntryByHash(0xC4886E60, "Boxy Fairing")
    AddTextEntryByHash(0xC8163E76, "Process Color Drifter")
    AddTextEntryByHash(0xC55624F5, "Secondary Lip Skirts")
    AddTextEntryByHash(0xC90440A6, "Primary Mirrors")
    AddTextEntryByHash(0xC352159F, "Winged Skirt")
    AddTextEntryByHash(0xC644785C, "Secondary Vented Hood")
    AddTextEntryByHash(0xC761031F, "Red On The Pisswasser Tee")
    AddTextEntryByHash(0xC4528878, "Overflod Gradient")
    AddTextEntryByHash(0xC9243729, "Extended Splitter")
    AddTextEntryByHash(0xCA7930AE, "Carbon Race Hood")
    AddTextEntryByHash(0xCAACB74A, "Secondary Extended Skirts")
    AddTextEntryByHash(0xCAFE8881, "HSW Competition Wing")
    AddTextEntryByHash(0xCB1BE386, "Race Ready Pack")
    AddTextEntryByHash(0xCB860BAE, "Carbon Side Bars")
    AddTextEntryByHash(0xCBDB7CAA,
        "This teasing little hardbody debuted at the tail end of the 80s, edging a tantalizing line between standard commuter vehicle and screeching drift monster, yet never quite committing to either. Headed to another day at the office? Tearing down Vinewood Boulevard at noon with your fourth speedball of the day already dissolving in your eight cup of single-origin cold-brew? Whatever your pleasure, Annis' iconic 4-seater is guaranteed to get you Hardy.~n~~n~- Missile Lock-On Jammer available")
    AddTextEntryByHash(0xCC4C311F, "Race Wing")
    AddTextEntryByHash(0xCC5EFA44, "Secondary Split Race Splitter")
    AddTextEntryByHash(0xCC406B82, "Carbon STD Division Spoiler")
    AddTextEntryByHash(0xCC596BB8, "Large Stock Spoiler")
    AddTextEntryByHash(0xCCB6B77E, "Secondary Rear Diffuser")
    AddTextEntryByHash(0xCCBA345F, "Secondary Hexagon Exhaust")
    AddTextEntryByHash(0xCD4A0667, "Secondary Twin Vented")
    AddTextEntryByHash(0xCD250BBD, "Carbon Race Diffuser")
    AddTextEntryByHash(0xCD5307D8, "Tint 2")
    AddTextEntryByHash(0xCDA1163B, "Plastic Ducktail")
    AddTextEntryByHash(0xCDC0A8F2, "Ego Chaser Autosport")
    AddTextEntryByHash(0xCDC73B62, "Slender Grille")
    AddTextEntryByHash(0xCDCA6A46, "Aggressive Vented Hood")
    AddTextEntryByHash(0xCDCCD61C, "Secondary Sunstrip")
    AddTextEntryByHash(0xCDF498DF, "Carbon Splitter")
    AddTextEntryByHash(0xCE1EC21C, "Bosozoku Wings")
    AddTextEntryByHash(0xCE7B5A31, "Carbon Wing Type II")
    AddTextEntryByHash(0xCE687183, "Race Diffuser")
    AddTextEntryByHash(0xCECA2AF8, "HELITOURS")
    AddTextEntryByHash(0xCED28F78, "Cruiser Panniers")
    AddTextEntryByHash(0xCED2824A, "Cup Graphics Orange")
    AddTextEntryByHash(0xCF9EDABD,
        "Dust off that old leather jacket, iron out those vintage Ranch jeans and crank Los Santos Rock Radio up to 11: you're about to become the final boss of mid-life crises. You weren't even alive when the Tampa GT came out, so no-one's going to believe that you blew what's left of your 401K for \"nostalgia reasons\", but with Vietnam-era rock blaring at full volume and a bored 19 year old staring at you with undisguised contempt in the passenger seat, who the hell cares?~n~~n~- Missile Lock-On Jammer available")
    AddTextEntryByHash(0xCF9594CD, "Matte Black w/ Light Tape")
    AddTextEntryByHash(0xCF51683D, "Sports Tuner Bumper")
    AddTextEntryByHash(0xCF64855C, "Boar Bash Bar")
    AddTextEntryByHash(0xCFA471AA, "Race Ducktail")
    AddTextEntryByHash(0xCFEFDB21, "Tuner Diffuser w/ Large Fins")
    AddTextEntryByHash(0xD02391E8, "The Slasher Clown")
    AddTextEntryByHash(0xD044AE54, "Carbon Strip")
    AddTextEntryByHash(0xD0E5227A, "V Shakotan Exhausts")
    AddTextEntryByHash(0xD0EC82A0, "Secondary Race Splitter")
    AddTextEntryByHash(0xD1B44FFD, "Tuner Wing")
    AddTextEntryByHash(0xD1D351F0, "Higashi Spirit")
    AddTextEntryByHash(0xD2AD958E, "Black Off-Road w/ Sec. Trim")
    AddTextEntryByHash(0xD2D7FBE8, "Camo Jack Sheepe Cap")
    AddTextEntryByHash(0xD2F08D53, "Factory White Stripe")
    AddTextEntryByHash(0xD3A67122, "Silhouette Style")
    AddTextEntryByHash(0xD3F50072, "Plastic Hawk Grille")
    AddTextEntryByHash(0xD6DA561C, "Tint 4")
    AddTextEntryByHash(0xD6DCF824, "Secondary Wing Vent")
    AddTextEntryByHash(0xD6F02DB3, "Record Holder White")
    AddTextEntryByHash(0xD6F31046, "Secondary Lip Splitter")
    AddTextEntryByHash(0xD8D5E55C, "Rally Wing")
    AddTextEntryByHash(0xD9AE4F18, "Heat Extractor")
    AddTextEntryByHash(0xD9CD51AB, "Plastic Rear Diffuser")
    AddTextEntryByHash(0xD9DF0885, "GT MK II Wing")
    AddTextEntryByHash(0xD11B76FE, "Secondary Downforce BGW")
    AddTextEntryByHash(0xD20B1463, "Secondary Hexagon Mesh")
    AddTextEntryByHash(0xD34D9411, "Carbon Large Splitter")
    AddTextEntryByHash(0xD39AB630, "Carbon Winged Skirt")
    AddTextEntryByHash(0xD94D762B, "Dual Long Bore Exhaust")
    AddTextEntryByHash(0xD95A98D6, "Carbon Hood")
    AddTextEntryByHash(0xD272BF67, "Roof Rack w/ Luggage")
    AddTextEntryByHash(0xD649CEAD, "Grille Removed")
    AddTextEntryByHash(0xD948A833, "Matte Black w/ Sec. Light Tape")
    AddTextEntryByHash(0xD3161A8E, "Brown Jumping Spider Mask")
    AddTextEntryByHash(0xD4373EE5, "Secondary Splitter")
    AddTextEntryByHash(0xD11314AE, "HSW Race Wing")
    AddTextEntryByHash(0xD407952A, "Carbon Utility w/ Sec. Trim")
    AddTextEntryByHash(0xD6677412, "Race Skirt")
    AddTextEntryByHash(0xDAE5625F, "Carbon Street Ducktail")
    AddTextEntryByHash(0xDB0C73D3, "Gauntlet Hellfire")
    AddTextEntryByHash(0xDB7756C2, "Plastic Vertical Grille")
    AddTextEntryByHash(0xDBA5BB4A, "Carbon Sport Vented Hood")
    AddTextEntryByHash(0xDBD857DC, "Slatted Grille")
    AddTextEntryByHash(0xDC4BB58D, "Plastic Street Splitter")
    AddTextEntryByHash(0xDC20D2C3, "Classic Roof Rack")
    AddTextEntryByHash(0xDC1072A3, "Primary Sunstrip")
    AddTextEntryByHash(0xDCBCE880, "Tint 1")
    AddTextEntryByHash(0xDCDDA12D, "Factory Color Stripe")
    AddTextEntryByHash(0xDCF09522, "Arrow Racing")
    AddTextEntryByHash(0xDD1B2E93, "Black On The Pisswasser Tee")
    AddTextEntryByHash(0xDD7AAA3A, "Pipes w/ Hood Delete")
    AddTextEntryByHash(0xDD7E76A2, "Muscle Killer Wing")
    AddTextEntryByHash(0xDD44B586, "Molded Arches")
    AddTextEntryByHash(0xDD892844, "Tint 1")
    AddTextEntryByHash(0xDDA85BBD, "Stripped Hood")
    AddTextEntryByHash(0xDDB5FD42, "Sec. Trimmed Carb. Race")
    AddTextEntryByHash(0xDDBC86D9, "Drift Show")
    AddTextEntryByHash(0xDDDF959D, "Hawk & Little Racing")
    AddTextEntryByHash(0xDDE55241, "Carbon Splitter")
    AddTextEntryByHash(0xDDF2D897, "STD Division Fenders")
    AddTextEntryByHash(0xDDF9479D,
        "Just when you think the Brits are finally going to come to terms with their newfound geopolitical irrelevance, they put out a banger like this, and the illusion limps on for another marketing cycle. With handling so good and responsiveness so intuitive that you won't know where your extremities end and machine begins, the Rapid GT X lets you play out your wildest biomechatronic fantasies on the open road, plus or minus any of the sexual stuff and/or the totally unjustified sense of entitlement. If that's your cup of milky tea.~n~~n~- Missile Lock-On Jammer available")
    AddTextEntryByHash(0xDE20B73A, "Carbon Street Ducktail")
    AddTextEntryByHash(0xDE92FBD1, "Titanium Slanted Side Exhaust")
    AddTextEntryByHash(0xDEA821F5, "Cup Graphics Blue")
    AddTextEntryByHash(0xDF076004, "Butterfly Blower")
    AddTextEntryByHash(0xDF082B21, "Pinned Competition Hood")
    AddTextEntryByHash(0xDF1DDF32, "Magnetics Track Pants")
    AddTextEntryByHash(0xDF50A08D, "Street Hood")
    AddTextEntryByHash(0xE0042BDB, "Plastic Twin Vented")
    AddTextEntryByHash(0xE09D8B5B, "Big Minimus Energy")
    AddTextEntryByHash(0xE0BBFEB2, "Wing Type II")
    AddTextEntryByHash(0xE0D0B1EE, "HSW Sport Grille")
    AddTextEntryByHash(0xE0D14907, "Carbon Angled Blast Pipes")
    AddTextEntryByHash(0xE1A49A2C, "Carbon Cutout Ducktail")
    AddTextEntryByHash(0xE1C2B41D, "Secondary Hood")
    AddTextEntryByHash(0xE1F13583, "Hands On Car Wash Overalls")
    AddTextEntryByHash(0xE2EA8F73, "Tuner Bumper")
    AddTextEntryByHash(0xE2FDADA5, "HSW Hood I")
    AddTextEntryByHash(0xE3B61C6F, "Hands On Car Wash Cap")
    AddTextEntryByHash(0xE3DC1BBD, "Carbon Cowl w/ Turbos")
    AddTextEntryByHash(0xE4BBE202, "Custom Wing")
    AddTextEntryByHash(0xE5CEDA98, "Carbon Street Skirts")
    AddTextEntryByHash(0xE5DDC46C, "Carbon Trunk Wing")
    AddTextEntryByHash(0xE6DB227D, "Carbon Downforce BGW")
    AddTextEntryByHash(0xE7BDB59C, "Carbon Simple Hood")
    AddTextEntryByHash(0xE7E4BFD2, "Camo Jack Sheepe Hoodie")
    AddTextEntryByHash(0xE7FCEA42, "Carbon Tip Lip Skirts")
    AddTextEntryByHash(0xE9B569E1, "Carbon Street Splitter")
    AddTextEntryByHash(0xE9BDB5DB, "Sport Lip Splitter")
    AddTextEntryByHash(0xE11A1539, "Boot Lip Spoiler")
    AddTextEntryByHash(0xE25C417B, "Secondary Mirrors")
    AddTextEntryByHash(0xE57CBB2C, "Declasse Bumper")
    AddTextEntryByHash(0xE58CF381, "Tint 3")
    AddTextEntryByHash(0xE59F8EDF, "Dual Short Bore Exhaust")
    AddTextEntryByHash(0xE70B6C27, "Carbon Rear Diffuser")
    AddTextEntryByHash(0xE74A89D6, "Stripped Rear Bumper")
    AddTextEntryByHash(0xE78D4A17, "Secondary Molded Arches")
    AddTextEntryByHash(0xE81C5228, "Drift Bumper w/ Charm")
    AddTextEntryByHash(0xE81FEBFB, "Secondary Heat Extractor")
    AddTextEntryByHash(0xE91E47E2, "Secondary w/ Sec. Light Tape")
    AddTextEntryByHash(0xE95E1FFE, "Everon Street Wing")
    AddTextEntryByHash(0xE206C4BD, "Ultra Shakotan Exhausts")
    AddTextEntryByHash(0xE281B279, "Secondary Large Splitter")
    AddTextEntryByHash(0xE481F74D, "Frank")
    AddTextEntryByHash(0xE602A48D, "Plastic w/ Chrome Hawk")
    AddTextEntryByHash(0xE810B452, "Hardy")
    AddTextEntryByHash(0xE954BFC4, "Carbon Utility Diffuser")
    AddTextEntryByHash(0xE1000E05, "Big Wing")
    AddTextEntryByHash(0xE2357FAC, "Tuner Diffuser w/ Fins")
    AddTextEntryByHash(0xE5576C9F, "Carbon Finned Skirts")
    AddTextEntryByHash(0xE6965AA8, "Carbon Wrapped Exhausts")
    AddTextEntryByHash(0xE88709AE, "Slim Rear w/ Black Trim")
    AddTextEntryByHash(0xE99352F9, "Black Stripe")
    AddTextEntryByHash(0xE344437E, "Secondary Finned Splitter")
    AddTextEntryByHash(0xE672834A, "Dummy label.")
    AddTextEntryByHash(0xEA2D61D6, "Titanium Tipped Exhausts")
    AddTextEntryByHash(0xEAA7DF14, "Secondary Wire Mesh Grille")
    AddTextEntryByHash(0xEAD5051D, "Magnetics Bomber Zipped")
    AddTextEntryByHash(0xEAE61306, "Painted Drag Spoiler")
    AddTextEntryByHash(0xEAFD4629, "Black Competition w/ Sec. Trim")
    AddTextEntryByHash(0xEB83E23D, "Primary Splitter")
    AddTextEntryByHash(0xEB153C4F, "Secondary Vented Hood")
    AddTextEntryByHash(0xEB943106, "Memphis Fracture")
    AddTextEntryByHash(0xEBBA4915, "The Bobcat Security Driver")
    AddTextEntryByHash(0xEBC8A7B1,
        "Like putting chicken on a pizza or ketchup on a Bolognese, some parts of Italian culture are best left alone unless you're prepared to go to war. Luckily for you, the LSCM is willing to defend itself against the least effective military force in world history, all so we can bring you the only car ever to be considered an improvement on a base Grotti. Buon Appetito.~n~~n~- Car Meet showcase vehicle: unique bodykit with limited customization~n~- Missile Lock-On Jammer built in")
    AddTextEntryByHash(0xEC0099D7, "Sec. Competition Splitter")
    AddTextEntryByHash(0xEC4E6001, "Carbon Wrapped Exhausts")
    AddTextEntryByHash(0xECCC9844, "Slanted Side Exhaust")
    AddTextEntryByHash(0xEDA2F535, "Carbon Straight Slats Grille")
    AddTextEntryByHash(0xEDA17B6E, "Plastic Slatted Grille")
    AddTextEntryByHash(0xEDD47B7C, "Vertical Grille")
    AddTextEntryByHash(0xEDE3A9E4, "Plastic w/ Chrome Slender")
    AddTextEntryByHash(0xEE0CD304, "Black Sunstrip")
    AddTextEntryByHash(0xEE31D352, "Secondary Sunstrip")
    AddTextEntryByHash(0xEE460AD5, "Arcana Penris")
    AddTextEntryByHash(0xEE594424, "Multi-Stripes Mono")
    AddTextEntryByHash(0xEF59B3CC, "Carbon Wing Skirts")
    AddTextEntryByHash(0xEFA7A924, "Nishi")
    AddTextEntryByHash(0xEFA15378, "Padded Roll Cage")
    AddTextEntryByHash(0xF026189B, "Carbon Triple Tip Exhaust")
    AddTextEntryByHash(0xF0334810, "HSW Hood II")
    AddTextEntryByHash(0xF0680E0D, "Atomic Racing Cap")
    AddTextEntryByHash(0xF08DEF29, "Titanium Track Exhaust")
    AddTextEntryByHash(0xF0B4560A, "Plastic Side Bars")
    AddTextEntryByHash(0xF3AC5CFA, "Primary w/ Light Tape")
    AddTextEntryByHash(0xF3CD9BA1, "Race Mirrors")
    AddTextEntryByHash(0xF3D73E91, "Street Wing")
    AddTextEntryByHash(0xF5A123E2, "Slim Rear Bumper")
    AddTextEntryByHash(0xF5C22F5C, "Plastic Arch Covers")
    AddTextEntryByHash(0xF5E06DB0, "Time Attack Bumper")
    AddTextEntryByHash(0xF5ECBFDE, "Hood Delete w/ Exposed Turbos")
    AddTextEntryByHash(0xF6B00F58, "Plastic Finned Skirts")
    AddTextEntryByHash(0xF7CE4FA6, "Grass Roots")
    AddTextEntryByHash(0xF7F45609, "Secondary Simple Hood")
    AddTextEntryByHash(0xF8C97B57, "Black Wire Mesh Grille")
    AddTextEntryByHash(0xF9D19517, "Enforcer Crash Bar")
    AddTextEntryByHash(0xF9FDEEF8, "Drift Kit")
    AddTextEntryByHash(0xF17DFD7D, "Roof Rack")
    AddTextEntryByHash(0xF25E0D4C, "Smoke on the Water Tee")
    AddTextEntryByHash(0xF42E00B2, "Chrome Horizontal Slats")
    AddTextEntryByHash(0xF91FDF50, "Competition Hood")
    AddTextEntryByHash(0xF94AD8BA, "Vented Hood")
    AddTextEntryByHash(0xF95ED177, "Hands On Car Wash Overalls")
    AddTextEntryByHash(0xF98E898F, "Plastic Tuner Splitter")
    AddTextEntryByHash(0xF298D24C, "Plastic Heavy Duty Diffuser")
    AddTextEntryByHash(0xF489B7C4, "Twin Vented Hood")
    AddTextEntryByHash(0xF492D46A, "I Survived Cayo Perico Tee")
    AddTextEntryByHash(0xF698BA73, "Street Ready Pack")
    AddTextEntryByHash(0xF919B409, "Plastic Race Splitter")
    AddTextEntryByHash(0xF3464B31, "Gravel Tribute")
    AddTextEntryByHash(0xF4989D33, "Secondary Mirrors")
    AddTextEntryByHash(0xF5309E15, "Secondary Wing")
    AddTextEntryByHash(0xF6435CB9, "Black Heavy Duty")
    AddTextEntryByHash(0xF8687FCB, "Secondary Street Skirts")
    AddTextEntryByHash(0xF24051B6, "Tint 6")
    AddTextEntryByHash(0xF58687BE, "Stripped Fenders")
    AddTextEntryByHash(0xF68743F1, "Secondary Street Wing")
    AddTextEntryByHash(0xF765894F, "Carbon Vented Hood")
    AddTextEntryByHash(0xF1900808, "Plastic w/ Sec. Extended")
    AddTextEntryByHash(0xF3176193, "CAR WASH")
    AddTextEntryByHash(0xF4191166, "Hell's Kitten")
    AddTextEntryByHash(0xF6326136, "Extended Skirts")
    AddTextEntryByHash(0xF7197231, "Sport Vented Hood")
    AddTextEntryByHash(0xFA1D0DD5, "Carbon Grille")
    AddTextEntryByHash(0xFA22C262, "Plastic w/ Secondary Slender")
    AddTextEntryByHash(0xFA6983D1, "Secondary Simple Skirt")
    AddTextEntryByHash(0xFAA8E124, "Twin Vented Hood")
    AddTextEntryByHash(0xFB66E3DE, "Race Hood")
    AddTextEntryByHash(0xFB588F37, "Large Chassis Mounted Wing")
    AddTextEntryByHash(0xFBE9F2CC, "Secondary Ducktail")
    AddTextEntryByHash(0xFC1D8B1A, "Razor Grille")
    AddTextEntryByHash(0xFCEC94D9, "Carbon Race Hood")
    AddTextEntryByHash(0xFD3FB7B9, "Drag Spoiler")
    AddTextEntryByHash(0xFDA14DA7, "Plastic Competition Ducktail")
    AddTextEntryByHash(0xFDBCC77E, "Tuner Wing")
    AddTextEntryByHash(0xFE1C4A30, "Smoke on the Water Tee")
    AddTextEntryByHash(0xFE56D0C2, "Carbon Vented Clean Hood")
    AddTextEntryByHash(0xFE62B177, "Buccaneer Hat")
    AddTextEntryByHash(0xFE67466C, "Sport Bumper")
    AddTextEntryByHash(0xFE209691, "Lip Skirts")
    AddTextEntryByHash(0xFEEF3736, "Hexagon Vented Trunk")
    AddTextEntryByHash(0xFF702B78, "Competition Wing")
    AddTextEntryByHash(0xFF905761, "Ghosts Exposed Backwards Cap")
    AddTextEntryByHash(0xFFF70DFB, "Titanium Street Exhaust")
end)
